name: CI (Client)

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - '.github/workflows/ci_client.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  packages:
    name: Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: ./client/package-lock.json
      - run: npm ci
        working-directory: client

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - packages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: ./client/package-lock.json
      - run: npm ci
        working-directory: client
      - run: npm run build
        working-directory: client
        env:
          NODE_ENV: production
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs:
      - packages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: ./client/package-lock.json
      - run: npm ci
        working-directory: client
      - run: npm run lint:nofix
        working-directory: client
  format:
    name: Format
    runs-on: ubuntu-latest
    needs:
      - packages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: ./client/package-lock.json
      - run: npm ci
        working-directory: client
      - run: npm run format:nofix
        working-directory: client
  typeCheck:
    name: Type Check
    runs-on: ubuntu-latest
    needs:
      - packages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: ./client/package-lock.json
      - run: npm ci
        working-directory: client
      - run: npm run type-check
        working-directory: client
